upstream datastore_cluster {
    server datastore1:8123;
    server datastore2:8123;
}

server {
    listen 8123;
    client_max_body_size 100M;
    location / {
        proxy_pass http://datastore_cluster;
    }
}
